#!/bin/bash

g++ -Iinclude -INon_Arch_Based_First_Stage/include  \
	# Added include lines first.
	src/*.cpp Non_Arch_Based_First_Stage/src/*.cpp  \
		#Then source codes.
		-o pacostrap
		#Then compiled software named `pacostrap.`
